name: 'Auto Label Per User'
description: 'Assigns a label according the PR author'
inputs:
  git-token:
    description: 'Token to add changelog file'
    required: true
  default-label:
    description: 'Default label'
    required: false
  user-team-map:
    description: 'A map of git users to labels'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'tag'
  color: 'green'
